
@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}


# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@email.com",
  "password": "123456",
  "cpf": "23234532245",
  "phone": "43232321"
}

###

# @name authenticate
POST  {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "john@email.com",
  "password": "123456"
}

###

# @name get user info
GET  {{baseUrl}}/me
Content-Type: application/json
Authorization: Bearer {{authToken}}
