
@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.token}}


# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@email.com",
  "password": "123456",
  "cpf": "23234532245",
  "phone": "43232321"
}

###

# @name authenticate
POST  {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "john@email.com",
  "password": "123456"
}

###

# @name get user info
GET  {{baseUrl}}/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name update_user 
PATCH   {{baseUrl}}/update/user
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "John Doe 2",
  "email": "johns@email.com",
  "cpf": "23234532245",
  "phone": "43232321"
}

###

# @name delete_user 
PUT    {{baseUrl}}/delete/user/2ac0fddb-90f8-48d7-a3ea-859b382be0d8
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_car
POST {{baseUrl}}/cars
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "chassisNumber": "1234567890",
  "licensePlate": "ABC-1234",
  "brand": "Volkswagen",
  "model": "Fusca",
  "manufacturingYear": 1970,
  "modelYear": 1970,
  "color": "Amarelo",
  "value": 30000
}

###

# @name create_customer
POST {{baseUrl}}/customers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Jane Doe",
  "cpf": "12345678901",
  "homePhone": "123456789",
  "streetAddress": "123 Main St",
  "state": "SP",
  "city": "São Paulo",
  "mobilePhone": "987654321",
  "income": 5000,
  "email": "jane@customer.com"
}

###

# @name find_all_customers
GET {{baseUrl}}/customers 
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name find_unique_customers
GET {{baseUrl}}/customers/41f8b36e-5b97-4423-bd63-da3f98d75455
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name delete_customers
PATCH  {{baseUrl}}/customers/41f8b36e-5b97-4423-bd63-da3f98d75455
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name update_customer
PUT  {{baseUrl}}/customer/d6a17b3e-d572-4fa9-aa33-9a9263f5a892
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Jane Doe",
  "cpf": "12345678901"
}


###

# @name find_many_cars
Get  {{baseUrl}}/cars
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name find_unique_car
Get  {{baseUrl}}/cars/33ab0010-69f5-400a-870c-4405db86b520
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_order
Post  {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "userId": "ae743bda-d4bb-431e-bb12-36d41e501e4f",
  "carId": "5338aab7-c6fb-4069-b3d3-0529cf709e96",
  "price": 10000,
  "orderType": "PURCHASE",
  "installmentsCount": 5,
  "customerId": "4d6d363e-0a21-4aaf-89f9-e740bdb1f51d"
}


###

# @name get_installments_by_orderId
Get {{baseUrl}}/installments/ea299c81-21fc-48fb-8ef1-419f7b0565b9
Content-Type: application/json
Authorization:  Bearer {{authToken}}

###

# @name find_customer_by_user_id
Get {{baseUrl}}/customers/71c1dea8-5bb3-4a05-b7de-f474c2baad78/user
Content-Type: application/json
Authorization:  Bearer {{authToken}}